import type { Observation, Profile, Comment } from "@/types";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "p1",
    stellar_address: "GBXYZ1234567890ABCDEF",
    username: "sporehunter",
    avatar_url: null,
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "p2",
    stellar_address: "GCABC9876543210FEDCBA",
    username: "mycoMaria",
    avatar_url: null,
    created_at: "2025-02-01T14:30:00Z",
  },
  {
    id: "p3",
    stellar_address: "GDDEF5555555555555555",
    username: "fungifinder",
    avatar_url: null,
    created_at: "2025-02-20T08:15:00Z",
  },
];

export const MOCK_OBSERVATIONS: Observation[] = [
  {
    id: "obs-1",
    observer_id: "p1",
    location: { lat: 40.4168, lng: -3.7038 },
    latitude: 40.4168,
    longitude: -3.7038,
    observed_at: "2025-03-01",
    cap_shape: "convex",
    cap_color: "brown",
    cap_size_cm: 8,
    cap_surface: "smooth",
    underside_type: "gills",
    underside_color: "white",
    underside_spacing: "crowded",
    gill_attachment: "free",
    stem_color: "white",
    stem_height_cm: 12,
    stem_hollow: false,
    stem_ring: true,
    flesh_color: "white",
    bruise_color: null,
    smell: "mushroomy",
    cap_margin: null, stem_shape: null, stem_surface: null, stem_base: null,
    has_volva: null, flesh_consistency: null, color_change: null,
    has_latex: null, latex_color: null, taste: null,
    substrate: "soil",
    habitat: "deciduous forest",
    growth_pattern: "scattered",
    ecological_role: null, associated_trees: null, season: null,
    spore_print_color: "dark brown",
    proposed_species: "Agaricus campestris",
    confidence: "pretty_sure",
    notes: "Found near oak trees in a clearing. Very classic field mushroom appearance.",
    status: "community_id",
    verified_species: "Agaricus campestris",
    created_at: "2025-03-01T16:20:00Z",
    updated_at: "2025-03-02T10:00:00Z",
    photos: [
      { id: "ph1", observation_id: "obs-1", storage_path: "/markers/placeholder.svg", photo_type: "cap_top", sort_order: 0, created_at: "2025-03-01T16:20:00Z" },
    ],
    observer: {
      id: "p1",
      stellar_address: "GBXYZ1234567890ABCDEF",
      username: "sporehunter",
      avatar_url: null,
      created_at: "2025-01-15T10:00:00Z",
    },
  },
  {
    id: "obs-2",
    observer_id: "p2",
    location: { lat: 40.4530, lng: -3.6883 },
    latitude: 40.453,
    longitude: -3.6883,
    observed_at: "2025-03-02",
    cap_shape: "funnel",
    cap_color: "orange",
    cap_size_cm: 5,
    cap_surface: "smooth",
    underside_type: "gills",
    underside_color: "orange",
    underside_spacing: "decurrent",
    gill_attachment: "decurrent",
    stem_color: "orange",
    stem_height_cm: 6,
    stem_hollow: false,
    stem_ring: false,
    flesh_color: "pale orange",
    bruise_color: null,
    smell: "fruity",
    cap_margin: null, stem_shape: null, stem_surface: null, stem_base: null,
    has_volva: null, flesh_consistency: null, color_change: null,
    has_latex: null, latex_color: null, taste: null,
    substrate: "soil",
    habitat: "coniferous forest",
    growth_pattern: "cluster",
    ecological_role: null, associated_trees: null, season: null,
    spore_print_color: "cream",
    proposed_species: "Cantharellus cibarius",
    confidence: "somewhat",
    notes: "Bright orange chanterelle-like mushroom under pine trees. False gills with forking pattern.",
    status: "discussing",
    verified_species: null,
    created_at: "2025-03-02T09:45:00Z",
    updated_at: "2025-03-02T09:45:00Z",
    photos: [],
    observer: {
      id: "p2",
      stellar_address: "GCABC9876543210FEDCBA",
      username: "mycoMaria",
      avatar_url: null,
      created_at: "2025-02-01T14:30:00Z",
    },
  },
  {
    id: "obs-3",
    observer_id: "p3",
    location: { lat: 40.3850, lng: -3.7500 },
    latitude: 40.385,
    longitude: -3.75,
    observed_at: "2025-03-03",
    cap_shape: "flat",
    cap_color: "white",
    cap_size_cm: 15,
    cap_surface: "scaly",
    underside_type: "pores",
    underside_color: "yellow",
    underside_spacing: null,
    gill_attachment: null,
    stem_color: "brown",
    stem_height_cm: 4,
    stem_hollow: false,
    stem_ring: false,
    flesh_color: "white",
    bruise_color: "blue",
    smell: "mushroomy",
    cap_margin: null, stem_shape: null, stem_surface: null, stem_base: null,
    has_volva: null, flesh_consistency: null, color_change: "bluing",
    has_latex: null, latex_color: null, taste: null,
    substrate: "dead wood",
    habitat: "mixed forest",
    growth_pattern: "alone",
    ecological_role: null, associated_trees: null, season: null,
    spore_print_color: null,
    proposed_species: null,
    confidence: "no_idea",
    notes: "Large bracket-like fungus on fallen log. Pores underneath turn blue when bruised.",
    status: "unverified",
    verified_species: null,
    created_at: "2025-03-03T14:10:00Z",
    updated_at: "2025-03-03T14:10:00Z",
    photos: [],
    observer: {
      id: "p3",
      stellar_address: "GDDEF5555555555555555",
      username: "fungifinder",
      avatar_url: null,
      created_at: "2025-02-20T08:15:00Z",
    },
  },
  {
    id: "obs-4",
    observer_id: "p1",
    location: { lat: 40.4300, lng: -3.7150 },
    latitude: 40.43,
    longitude: -3.715,
    observed_at: "2025-03-04",
    cap_shape: "bell-shaped",
    cap_color: "red with white spots",
    cap_size_cm: 12,
    cap_surface: "scaly",
    underside_type: "gills",
    underside_color: "white",
    underside_spacing: "crowded",
    gill_attachment: "free",
    stem_color: "white",
    stem_height_cm: 18,
    stem_hollow: true,
    stem_ring: true,
    flesh_color: "white",
    bruise_color: null,
    smell: "none",
    cap_margin: null, stem_shape: "bulbous", stem_surface: null, stem_base: "with_volva",
    has_volva: true, flesh_consistency: null, color_change: null,
    has_latex: null, latex_color: null, taste: null,
    substrate: "soil",
    habitat: "mixed forest",
    growth_pattern: "alone",
    ecological_role: "mycorrhizal", associated_trees: "birch", season: "autumn",
    spore_print_color: "white",
    proposed_species: "Amanita muscaria",
    confidence: "pretty_sure",
    notes: "Classic fly agaric! Iconic red cap with white warts. Found near birch trees.",
    status: "community_id",
    verified_species: "Amanita muscaria",
    created_at: "2025-03-04T11:30:00Z",
    updated_at: "2025-03-05T08:00:00Z",
    photos: [],
    observer: {
      id: "p1",
      stellar_address: "GBXYZ1234567890ABCDEF",
      username: "sporehunter",
      avatar_url: null,
      created_at: "2025-01-15T10:00:00Z",
    },
  },
  {
    id: "obs-5",
    observer_id: "p2",
    location: { lat: 40.4700, lng: -3.6700 },
    latitude: 40.47,
    longitude: -3.67,
    observed_at: "2025-03-05",
    cap_shape: "irregular",
    cap_color: "dark brown",
    cap_size_cm: 6,
    cap_surface: "wrinkled",
    underside_type: "smooth",
    underside_color: "cream",
    underside_spacing: null,
    gill_attachment: null,
    stem_color: "cream",
    stem_height_cm: 5,
    stem_hollow: true,
    stem_ring: false,
    flesh_color: "cream",
    bruise_color: null,
    smell: "none",
    cap_margin: null, stem_shape: null, stem_surface: null, stem_base: null,
    has_volva: null, flesh_consistency: null, color_change: null,
    has_latex: null, latex_color: null, taste: null,
    substrate: "soil",
    habitat: "garden",
    growth_pattern: "scattered",
    ecological_role: null, associated_trees: null, season: null,
    spore_print_color: null,
    proposed_species: "Morchella esculenta",
    confidence: "guess",
    notes: "Honeycomb-like cap structure. Found in garden after rain. Could be a morel?",
    status: "discussing",
    verified_species: null,
    created_at: "2025-03-05T07:15:00Z",
    updated_at: "2025-03-05T07:15:00Z",
    photos: [],
    observer: {
      id: "p2",
      stellar_address: "GCABC9876543210FEDCBA",
      username: "mycoMaria",
      avatar_url: null,
      created_at: "2025-02-01T14:30:00Z",
    },
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "c1",
    observation_id: "obs-1",
    author_id: "p2",
    body: "Great find! The dark brown spore print and free gills are classic Agaricus campestris features.",
    comment_type: "agree",
    suggested_species: null,
    created_at: "2025-03-01T18:00:00Z",
    author: MOCK_PROFILES[1],
  },
  {
    id: "c2",
    observation_id: "obs-2",
    author_id: "p1",
    body: "The forking false gills do look like chanterelle. But could also be Hygrophoropsis aurantiaca (false chanterelle). Does the flesh snap cleanly like an egg white?",
    comment_type: "discussion",
    suggested_species: null,
    created_at: "2025-03-02T12:00:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "c3",
    observation_id: "obs-2",
    author_id: "p3",
    body: "I think this might be a false chanterelle based on the habitat. True chanterelles are rarer in pure pine stands here.",
    comment_type: "suggest",
    suggested_species: "Hygrophoropsis aurantiaca",
    created_at: "2025-03-02T14:30:00Z",
    author: MOCK_PROFILES[2],
  },
  {
    id: "c4",
    observation_id: "obs-3",
    author_id: "p1",
    body: "The blue bruising on a polypore growing on dead wood is interesting. Could be in the Boletus family? A spore print would help narrow it down.",
    comment_type: "discussion",
    suggested_species: null,
    created_at: "2025-03-03T16:45:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "c5",
    observation_id: "obs-4",
    author_id: "p3",
    body: "Definitely Amanita muscaria. The white warts on red cap and the volva are unmistakable. Beautiful specimen!",
    comment_type: "agree",
    suggested_species: null,
    created_at: "2025-03-04T15:00:00Z",
    author: MOCK_PROFILES[2],
  },
  {
    id: "c6",
    observation_id: "obs-5",
    author_id: "p3",
    body: "The honeycomb structure is consistent with Morchella. Be careful though - Gyromitra (false morel) can look similar. Does the cap attach at the base of the stem?",
    comment_type: "discussion",
    suggested_species: null,
    created_at: "2025-03-05T10:00:00Z",
    author: MOCK_PROFILES[2],
  },
];

export function getObservationById(id: string): Observation | undefined {
  const obs = MOCK_OBSERVATIONS.find((o) => o.id === id);
  if (obs) {
    return {
      ...obs,
      comments: MOCK_COMMENTS.filter((c) => c.observation_id === id),
    };
  }
  return undefined;
}

export function getObservationsByObserver(observerId: string): Observation[] {
  return MOCK_OBSERVATIONS.filter((o) => o.observer_id === observerId);
}

export function getProfileByAddress(address: string): Profile | undefined {
  return MOCK_PROFILES.find((p) => p.stellar_address === address);
}
